FROM node:24.13.0-alpine3.23

# bcrypt and git deps for dev
RUN apk add --no-cache make gcc g++ python3 git

WORKDIR /app

COPY api/package*.json ./

RUN npm ci

COPY api/ .

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]